# MARKDOWN Settings
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
#highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title:  'Attila Kling blog'
tagline: 'blog about programming'
description: 'A technical blog about programming'
url: 'http://localhost:4000'
baseurl: '/'
#paginate: 5

#Personal
author:
  name: 'Attila Kling'
  url: https://twitter.com/attilakling
  email: jimmyfly10@gmail.com

twitter_username: attilakling
github_username: jim-y

# Custom vars
version: 0.0.1

sass:
    sass_dir: _sass

exclude:
  - Gemfile
  - Gemfile.lock

repository: https://github.com/jim-y/blog
