markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title:  'Blog | Jim-Y'
tagline: 'blog about programming'
description: 'A technical blog about programming'
url: 'http://localhost:4000'
baseurl: '/blog'
#paginate: 5

#Personal
author:
  name: 'Attila Kling'
  url: https://twitter.com/attilakling
  email: jimmyfly10@gmail.com
  twitter: '@attilakling'

# Custom vars
version: 0.0.1

sass:
    sass_dir: _sass

exclude:
  - Gemfile
  - Gemfile.lock

repository: 'jim-y/blog'
